name: py39
channels:
  - conda-forge
dependencies:
  - pip
  - xgboost
  - lightgbm
  - catboost
  - mlxtend
  - gensim
  - vowpalwabbit
  - hyperopt
  - deap
  - update_checker
  - tqdm
  - stopit
  - scikit-mdr
  - skrebate
  - tpot
  - yellowbrick
  - spacy
  - gplearn
  - shap
  - lime
  - gpxpy
  - arrow
  - haversine
  - toolz
  - cytoolz
  - sacred
  - plotly
  - missingno
  - pandas-profiling
  - pip:
      - git+https://github.com/nicta/dora.git
      - tables
      - sklearn-deap
      - trueskill
      - kmapper
      - sexmachine
      - heamy
      - geohash
      - langid
      - s2sphere
      - fitter
      - vida
      - delorean
      - skope-rules