name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Name of the release  (ie 5.5.0)'
        required: true
      releaseDescription:
        description: "A short description of the release content (will be added the PR's body)"
        required: false
      nextReleaseVersion:
        description: 'Next release version (1.1.1-snapshot)'
        required: true
jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Change version number and set new snapshot version
      run: |
        printf '${{ github.event.inputs.releaseVersion }}' > version.txt
        printf '${{ github.event.inputs.nextReleaseVersion }}' > snapshot.txt
    - name: Change version in package.json
      uses: sergeysova/jq-action@v2
      with:
        cmd: "jq --arg a '${{ github.event.inputs.releaseVersion }}' '.version = $a' package.json > tmp.$$.json && mv tmp.$$.json package.json"
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Install gitmoji-changelog
      run: npm install -g gitmoji-changelog
    - name: Update Changelog
      run: gitmoji-changelog
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add version.txt
        git add snapshot.txt
        git add package.json
        git add CHANGELOG.md
        git commit --message ":bookmark: Prepare release ${{ github.event.inputs.releaseVersion }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.releaseVersion }}
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.releaseVersion }}
       base: main
       title: v${{ github.event.inputs.releaseVersion }} into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
           Description : ${{ github.event.inputs.releaseDescription }}
    - name: Create pull request to develop
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/v${{ github.event.inputs.releaseVersion }}
          base: develop
          title: v${{ github.event.inputs.releaseVersion }} into develop
          reviewers: ${{ github.event.issue.user.login }}
          body: |
              Hi!
              This PR was created in response workflow running.
              I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
              Description : ${{ github.event.inputs.releaseDescription }}