name: Tag Release
on:
    push:
        branches: [ main ]
jobs:
    tag_release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Initialize mandatory git config
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email noreply@github.com
            - name: Setup release information
              run: |
                  versionNumber=`cat ./VERSION.txt`
                  echo "VERSION_NUMBER=$versionNumber" >> $GITHUB_ENV
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ env.VERSION_NUMBER }}
                release_name: v${{ env.VERSION_NUMBER }}
                body_path: ./CHANGELOG.md
                draft: false
                prerelease: false